"""second migration

Revision ID: 347ee42634a7
Revises: 3b9f071f66a3
Create Date: 2023-01-04 10:52:42.950303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347ee42634a7'
down_revision = '3b9f071f66a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datos_personales', schema=None) as batch_op:
        batch_op.alter_column('carrera',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=90),
               existing_nullable=False)
        batch_op.alter_column('facultad',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=90),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datos_personales', schema=None) as batch_op:
        batch_op.alter_column('facultad',
               existing_type=sa.String(length=90),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.alter_column('carrera',
               existing_type=sa.String(length=90),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###
