"""first migration

Revision ID: 3b9f071f66a3
Revises: 
Create Date: 2023-01-02 18:18:59.619948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9f071f66a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datos_academicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio', sa.String(length=45), nullable=False),
    sa.Column('ano_culminacion_estudio', sa.String(length=4), nullable=False),
    sa.Column('num_postulacion', sa.Integer(), nullable=False),
    sa.Column('otra_carrera', sa.String(length=60), nullable=False),
    sa.Column('tipo_preparacion', sa.String(length=20), nullable=False),
    sa.Column('motivo_postulacion', sa.String(length=45), nullable=False),
    sa.Column('escuela_motivo', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datos_madre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellido_pa', sa.String(length=20), nullable=False),
    sa.Column('apellido_ma', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('esta_vivo', sa.Boolean(), nullable=False),
    sa.Column('estado_civil', sa.String(length=15), nullable=False),
    sa.Column('nivel_educacion', sa.String(length=30), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=10), nullable=False),
    sa.Column('pais', sa.String(length=20), nullable=False),
    sa.Column('departamento', sa.String(length=20), nullable=False),
    sa.Column('provincia', sa.String(length=20), nullable=False),
    sa.Column('distrito', sa.String(length=20), nullable=False),
    sa.Column('zona_rural', sa.Boolean(), nullable=False),
    sa.Column('discapacidad_trabajo', sa.Boolean(), nullable=False),
    sa.Column('primera_ocupacion', sa.String(length=45), nullable=False),
    sa.Column('segunda_ocupacion', sa.String(length=45), nullable=False),
    sa.Column('ingresos', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datos_madre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datos_madre_departamento'), ['departamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_datos_madre_distrito'), ['distrito'], unique=False)
        batch_op.create_index(batch_op.f('ix_datos_madre_pais'), ['pais'], unique=False)
        batch_op.create_index(batch_op.f('ix_datos_madre_provincia'), ['provincia'], unique=False)

    op.create_table('datos_padre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellido_pa', sa.String(length=20), nullable=False),
    sa.Column('apellido_ma', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('esta_vivo', sa.Boolean(), nullable=False),
    sa.Column('estado_civil', sa.String(length=15), nullable=False),
    sa.Column('nivel_educacion', sa.String(length=30), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=10), nullable=False),
    sa.Column('pais', sa.String(length=20), nullable=False),
    sa.Column('departamento', sa.String(length=20), nullable=False),
    sa.Column('provincia', sa.String(length=20), nullable=False),
    sa.Column('distrito', sa.String(length=20), nullable=False),
    sa.Column('zona_rural', sa.Boolean(), nullable=False),
    sa.Column('discapacidad_trabajo', sa.Boolean(), nullable=False),
    sa.Column('primera_ocupacion', sa.String(length=45), nullable=False),
    sa.Column('segunda_ocupacion', sa.String(length=45), nullable=False),
    sa.Column('ingresos', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datos_padre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datos_padre_departamento'), ['departamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_datos_padre_distrito'), ['distrito'], unique=False)
        batch_op.create_index(batch_op.f('ix_datos_padre_pais'), ['pais'], unique=False)
        batch_op.create_index(batch_op.f('ix_datos_padre_provincia'), ['provincia'], unique=False)

    op.create_table('datos_personales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_matricula', sa.String(length=6), nullable=False),
    sa.Column('carrera', sa.String(length=60), nullable=False),
    sa.Column('facultad', sa.String(length=60), nullable=False),
    sa.Column('apellido_pa', sa.String(length=20), nullable=False),
    sa.Column('apellido_ma', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('discapacitado', sa.Boolean(), nullable=False),
    sa.Column('estado_civil', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('celular', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datos_personales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datos_personales_celular'), ['celular'], unique=True)
        batch_op.create_index(batch_op.f('ix_datos_personales_codigo_matricula'), ['codigo_matricula'], unique=True)
        batch_op.create_index(batch_op.f('ix_datos_personales_dni'), ['dni'], unique=True)
        batch_op.create_index(batch_op.f('ix_datos_personales_email'), ['email'], unique=True)

    op.create_table('ingresantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('modalidad', sa.String(length=45), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('procedencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=20), nullable=False),
    sa.Column('departamento', sa.String(length=20), nullable=False),
    sa.Column('provincia', sa.String(length=20), nullable=False),
    sa.Column('distrito', sa.String(length=20), nullable=False),
    sa.Column('tipo_vivienda', sa.String(length=20), nullable=False),
    sa.Column('material_vivienda', sa.String(length=15), nullable=False),
    sa.Column('num_habitaciones', sa.Integer(), nullable=False),
    sa.Column('zona_rural', sa.Boolean(), nullable=False),
    sa.Column('barrio', sa.String(length=30), nullable=False),
    sa.Column('direccion', sa.String(length=30), nullable=False),
    sa.Column('luz_electrica', sa.Boolean(), nullable=False),
    sa.Column('agua_potable', sa.Boolean(), nullable=False),
    sa.Column('desague', sa.Boolean(), nullable=False),
    sa.Column('telefono_fijo', sa.Boolean(), nullable=False),
    sa.Column('internet', sa.Boolean(), nullable=False),
    sa.Column('television_cable', sa.Boolean(), nullable=False),
    sa.Column('radio', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procedencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedencia_departamento'), ['departamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_procedencia_distrito'), ['distrito'], unique=False)
        batch_op.create_index(batch_op.f('ix_procedencia_pais'), ['pais'], unique=False)
        batch_op.create_index(batch_op.f('ix_procedencia_provincia'), ['provincia'], unique=False)

    op.create_table('residencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=20), nullable=False),
    sa.Column('departamento', sa.String(length=20), nullable=False),
    sa.Column('provincia', sa.String(length=20), nullable=False),
    sa.Column('distrito', sa.String(length=20), nullable=False),
    sa.Column('tipo_vivienda', sa.String(length=20), nullable=False),
    sa.Column('material_vivienda', sa.String(length=15), nullable=False),
    sa.Column('num_habitaciones', sa.Integer(), nullable=False),
    sa.Column('zona_rural', sa.Boolean(), nullable=False),
    sa.Column('barrio', sa.String(length=30), nullable=False),
    sa.Column('direccion', sa.String(length=30), nullable=False),
    sa.Column('referencia', sa.String(length=45), nullable=False),
    sa.Column('luz_electrica', sa.Boolean(), nullable=False),
    sa.Column('agua_potable', sa.Boolean(), nullable=False),
    sa.Column('desague', sa.Boolean(), nullable=False),
    sa.Column('telefono_fijo', sa.Boolean(), nullable=False),
    sa.Column('internet', sa.Boolean(), nullable=False),
    sa.Column('television_cable', sa.Boolean(), nullable=False),
    sa.Column('radio', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('residencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_residencia_departamento'), ['departamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_residencia_distrito'), ['distrito'], unique=False)
        batch_op.create_index(batch_op.f('ix_residencia_pais'), ['pais'], unique=False)
        batch_op.create_index(batch_op.f('ix_residencia_provincia'), ['provincia'], unique=False)

    op.create_table('situacion_familiar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dependencia_padre', sa.Boolean(), nullable=False),
    sa.Column('dependencia_madre', sa.Boolean(), nullable=False),
    sa.Column('dependencia_hermanos', sa.Boolean(), nullable=False),
    sa.Column('dependencia_conyuge', sa.Boolean(), nullable=False),
    sa.Column('dependencia_pariente', sa.Boolean(), nullable=False),
    sa.Column('autosostenimiento', sa.Boolean(), nullable=False),
    sa.Column('vive_con', sa.String(length=10), nullable=False),
    sa.Column('contacto_nombre', sa.String(length=80), nullable=False),
    sa.Column('contacto_parentesco', sa.String(length=15), nullable=False),
    sa.Column('contacto_direccion', sa.String(length=45), nullable=False),
    sa.Column('contacto_lugar', sa.String(length=45), nullable=False),
    sa.Column('contacto_celular', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=64), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('datos_personales_id', sa.Integer(), nullable=False),
    sa.Column('procedencia_id', sa.Integer(), nullable=False),
    sa.Column('residencia_id', sa.Integer(), nullable=False),
    sa.Column('situacion_familiar_id', sa.Integer(), nullable=False),
    sa.Column('datos_madre_id', sa.Integer(), nullable=False),
    sa.Column('datos_padre_id', sa.Integer(), nullable=False),
    sa.Column('datos_academicos_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['datos_academicos_id'], ['datos_academicos.id'], ),
    sa.ForeignKeyConstraint(['datos_madre_id'], ['datos_madre.id'], ),
    sa.ForeignKeyConstraint(['datos_padre_id'], ['datos_padre.id'], ),
    sa.ForeignKeyConstraint(['datos_personales_id'], ['datos_personales.id'], ),
    sa.ForeignKeyConstraint(['procedencia_id'], ['procedencia.id'], ),
    sa.ForeignKeyConstraint(['residencia_id'], ['residencia.id'], ),
    sa.ForeignKeyConstraint(['situacion_familiar_id'], ['situacion_familiar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_codigo'), ['codigo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_codigo'))

    op.drop_table('users')
    op.drop_table('situacion_familiar')
    with op.batch_alter_table('residencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_residencia_provincia'))
        batch_op.drop_index(batch_op.f('ix_residencia_pais'))
        batch_op.drop_index(batch_op.f('ix_residencia_distrito'))
        batch_op.drop_index(batch_op.f('ix_residencia_departamento'))

    op.drop_table('residencia')
    with op.batch_alter_table('procedencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedencia_provincia'))
        batch_op.drop_index(batch_op.f('ix_procedencia_pais'))
        batch_op.drop_index(batch_op.f('ix_procedencia_distrito'))
        batch_op.drop_index(batch_op.f('ix_procedencia_departamento'))

    op.drop_table('procedencia')
    op.drop_table('ingresantes')
    with op.batch_alter_table('datos_personales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datos_personales_email'))
        batch_op.drop_index(batch_op.f('ix_datos_personales_dni'))
        batch_op.drop_index(batch_op.f('ix_datos_personales_codigo_matricula'))
        batch_op.drop_index(batch_op.f('ix_datos_personales_celular'))

    op.drop_table('datos_personales')
    with op.batch_alter_table('datos_padre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datos_padre_provincia'))
        batch_op.drop_index(batch_op.f('ix_datos_padre_pais'))
        batch_op.drop_index(batch_op.f('ix_datos_padre_distrito'))
        batch_op.drop_index(batch_op.f('ix_datos_padre_departamento'))

    op.drop_table('datos_padre')
    with op.batch_alter_table('datos_madre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datos_madre_provincia'))
        batch_op.drop_index(batch_op.f('ix_datos_madre_pais'))
        batch_op.drop_index(batch_op.f('ix_datos_madre_distrito'))
        batch_op.drop_index(batch_op.f('ix_datos_madre_departamento'))

    op.drop_table('datos_madre')
    op.drop_table('datos_academicos')
    # ### end Alembic commands ###
